---
title: "Simulations of occurrence cubes"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE)

library(sf)
library(tidyverse)
```

# Simulate data

First we simulate points.

```{r}
# Simulate points
sim_points <- function(n, xlim = c(62000, 63000), ylim = c(182000, 183000),
                       add_points = NULL, seed = 123) {
  set.seed(123)
  if (!is.null(add_points)) {
    out <- tibble(
        lat = runif(n, ylim[1], ylim[2]),
        long = runif(n, xlim[1], xlim[2])) %>%
      bind_rows(add_points[,1:2]) %>%
      st_as_sf(coords = c("long", "lat"), crs = st_crs(31370)) %>%
      mutate(coordinateUncertaintyInMeters = 
               c(abs(rnorm(10, 100, 500)), 
                 add_points$coordinateUncertaintyInMeters))
  } else {
    out <- tibble(
        lat = runif(n, ylim[1], ylim[2]),
        long = runif(n, xlim[1], xlim[2])) %>%
      st_as_sf(coords = c("long", "lat"), crs = st_crs(31370)) %>%
      mutate(coordinateUncertaintyInMeters = abs(rnorm(10, 100, 500)))
  }

  out %>%
    cbind(st_coordinates(out)) %>%
    rename(x = X, y = Y)
}
```

```{r}
test_points <- sim_points(10, add_points = tibble(lat = 183900, long = 64000,
                          coordinateUncertaintyInMeters = 50))

test_circles <- test_points %>%
  st_buffer(test_points$coordinateUncertaintyInMeters)
```

We create a custom grid around the points.

```{r}
# Create grid
create_grid <- function(spacing, circles) {
  grid_spacing <- spacing  # size of squares, in units of the CRS
  grid <- st_make_grid(circles, square = T, 
                       cellsize = c(grid_spacing, grid_spacing)) %>%
    st_as_sf() %>%
    mutate(id = row_number())
  
  return(grid)
}

grid_df <- create_grid(500, test_circles)
```

Visualisation:

```{r}
ggplot() +
  geom_sf(data = grid_df) +
  geom_sf(data = test_circles, fill = alpha("white", 0))
```


# Simulate cubes

We create a function to simulate cubes.

```{r}
sim_cubes <- function(n_sim, points, grid, seed = 123, print = 100) {
  out <- vector(mode = "list", length = n_sim)
  
  set.seed(seed)
  
  for (i in 1:n_sim) {
    if (i %% print == 0) {
      message(paste0("* Generating cube ", i, "/", n_sim))
    }
    # Get random point
    test_points <-
      points %>%
      st_drop_geometry() %>%
      mutate(random_angle = runif(nrow(points), 0, 2*pi),
             random_r = sqrt(runif(nrow(points), 0, 1)) * 
               coordinateUncertaintyInMeters)
    
    test_points2 <-
      test_points %>%
      mutate(x_new = x + random_r * cos(random_angle),
             y_new = y + random_r * sin(random_angle)) %>%
      st_as_sf(coords = c("x_new", "y_new"), crs = st_crs(31370))
    
    # We assign each occurrence to a grid cell
    intersect_grid <- st_intersection(test_points2, grid)
    
    # Aggregate to get the cube
    occ_cube <- intersect_grid %>%
      st_drop_geometry() %>%
      group_by(id) %>%
      summarize(n = n(),
                min_coord_uncertainty = min(coordinateUncertaintyInMeters)) %>%
      ungroup() %>%
      mutate(sim = i)
    
    out[[i]] <- occ_cube
  }
  
  final_occs <- do.call(rbind.data.frame, out)

  # Add zeroes
  design <- expand_grid(id = grid$id, sim = seq_len(n_sim))
  
  out_df <- final_occs %>%
    full_join(design, by = join_by(id, sim)) %>%
    mutate(n = ifelse(is.na(n), 0, n))
  
  return(out_df)
}
```

```{r}
final_df <- sim_cubes(1000, test_points, grid_df)
```


## Calculate statistics

```{r}
# Summary statistics
summary_df <- final_df %>%
  group_by(id) %>%
  summarise(mean_n = mean(n),
            sd_n = sd(n),
            median_n = median(n),
            iqr_n = IQR(n))

# Calculate effective number of occurrences
int_grid_circle <- test_circles %>%
  mutate(circle_area = st_area(test_circles),
         point_id = row_number()) %>%
  st_intersection(grid_df)

props <- int_grid_circle %>%
  mutate(area = st_area(int_grid_circle),
         prop = area / circle_area)

summary_grid_props <- props %>%
  st_drop_geometry() %>%
  group_by(id) %>%
  summarise(expected_n = sum(prop)) %>%
  full_join(grid_df, by = join_by(id)) %>%
  st_as_sf() %>%
  mutate(expected_n = ifelse(is.na(expected_n), 0, expected_n))

# Calculate probability of occupancy
occupancy_prob_df <- final_df %>% 
  count(id, n, name = "total") %>%
  group_by(id) %>% 
  mutate(occupancy = ifelse(n == 0, 0, 1)) %>%
  group_by(id, occupancy) %>%
  summarise(n = sum(total)) %>%
  group_by(id) %>%
  mutate(sum = sum(n)) %>%
  ungroup() %>%
  mutate(p = n / sum)

design <-  occupancy_prob_df %>%
  expand(id, occupancy)

occupancy_prob_df <- occupancy_prob_df %>%
  full_join(design, by = join_by(id, occupancy)) %>%
  mutate(across(where(is.numeric), ~ coalesce(.x, 0))) %>%
  group_by(id) %>%
  mutate(sum = sum(n)) %>%
  ungroup() %>%
  filter(occupancy == 1)
```

## Visualise simulations

```{r}
example_cells <- 14:25
```

Example for grid cells `r example_cells`

```{r}
final_df %>% 
  filter(id %in% example_cells) %>%
  mutate(occupancy = ifelse(n == 0, "0", ">1")) %>%
  ggplot(aes(x = n)) + 
    geom_bar(aes(fill = occupancy)) +
    geom_text(data = summary_df %>% filter(id %in% example_cells), 
              aes(x = 3, y = 750, label = paste0("mean: ", mean_n, "\n",
                                                 "sd: ", round(sd_n, 3), "\n",
                                                 "median: ", median_n))) +
    facet_wrap(~id) +
    labs(y = "frequency")
```


# Visualise statistics

```{r, fig.height=10}
summary_df %>%
  select(id, mean_n, median_n) %>%
  full_join(summary_grid_props, by = join_by(id)) %>%
  mutate(expected_n_rounded = round(expected_n)) %>%
  pivot_longer(cols = c(mean_n, median_n, expected_n, expected_n_rounded), 
               names_to = "measure", values_to = "n") %>%
  st_as_sf() %>%
  ggplot() +
    geom_sf(aes(fill = n)) +
    geom_sf_text(aes(label = round(n, 3))) +
    geom_sf(data = test_circles, fill = alpha("white", 0), 
            colour = "firebrick") +
    scale_fill_gradient2() +
    labs(fill = "number of occurrences", x = "", y = "") +
    facet_wrap(~measure, ncol = 2) +
    theme(legend.position = "bottom")
```

```{r}
full_join(grid_df, occupancy_prob_df, by = join_by(id)) %>%
  mutate(cat = case_when(
    p <= 0.25 ~ "0-0.25",
    p > 0.25 & p <= 0.5 ~ "0.25-0.5",
    p > 0.5 & p <= 0.75 ~ "0.5-0.75",
    TRUE ~ "0.75-1.0"
  )) %>%
  ggplot() +
  geom_sf(aes(fill = cat)) +
  geom_sf_text(aes(label = round(p, 3))) +
  geom_sf(data = test_circles, fill = alpha("white", 0), 
          colour = "firebrick") +
  labs(fill = "P(n >=1)", title = "Probability of occupancy",
       x = "", y = "")
```
